default: &default
  adapter: postgresql
  host:     <%= ENV["POSTGRES_HOST"] %>
  username: <%= ENV["POSTGRES_USER"] %>
  password: <%= ENV["POSTGRES_PASSWORD"] %>
  encoding: utf8
  min_messages: warning
  pool: 2
  timeout: 5000

development:
  <<: *default
  database: wingle_development

deployment:
  <<: *default
  database: wingle_development

test: &test
  <<: *default
  database: wingle_test

production:
  <<: *default
  database: wingle_production

cucumber:
  <<: *test
