development:
  id: "<%=ENV['FACEBOOK_APP_ID']%>"
  secret_key: "<%=ENV['FACEBOOK_APP_SECRET_KEY']%>"

test:
  id: "<%=ENV['FACEBOOK_APP_ID']%>"
  secret_key: "<%=ENV['FACEBOOK_APP_SECRET_KEY']%>"

production:
  id: "<%=ENV['FACEBOOK_APP_ID']%>"
  secret_key: "<%=ENV['FACEBOOK_APP_SECRET_KEY']%>"
