paths:
  logo:   'logo.svg'
  logout: '/admins/sign_out'

  menu_links:
    admins:
      name: 'Administradores'
      path: admin_admins_path
    positions:
      name: 'Cargos'
      path: admin_positions_path
    specialties:
      name: 'Especialidades'
      path: admin_specialties_path
    # translations:
    #   name: 'Textos'
    #   path: admin_translations_path
    terms:
      name: 'Termos'
      path: admin_terms_path
    services:
      name: 'Pacote de Serviços'
      path: admin_package_services_path
    locales:
      name: 'Localidade'
      path: admin_locales_path
    sectors:
      name: 'Setores'
      path: admin_sectors_path
    sizes:
      name: 'Portes'
      path: admin_company_sizes_path
    modes:
      name: 'Momentos da Empresa'
      path: admin_modes_path
    relevances:
      name: 'Relevâncias'
      path: admin_relevances_path
    areas:
      name: 'Áreas'
      path: admin_areas_path
    title_list:
      name: 'Lista de Títulos'
      path: admin_title_lists_path
    range_list:
      name: 'Lista de Alcances'
      path: admin_range_lists_path
    education_list:
      name: 'Lista de Escolaridades'
      path: admin_education_lists_path
    language_list:
      name: 'Lista de Línguas'
      path: admin_language_lists_path
    language_level_list:
      name: 'Lista de Níveis de Línguas'
      path: admin_language_level_lists_path
    nofsalaries_list:
      name: 'Lista de Nofsalaries'
      path: admin_nofsalaries_lists_path
    benefits_list:
      name: 'Lista de Benefícios'
      path: admin_benefits_lists_path
    annual_claim_rate_list:
      name: 'Lista de Reinvidicações Anuais'
      path: admin_annual_claim_rate_lists_path
    status_list:
      name: 'Lista de Status'
      path: admin_status_lists_path
    step_list:
      name: 'Lista de Etapas'
      path: admin_step_lists_path
    sort_list:
      name: 'Lista de Ordenações'
      path: admin_sort_lists_path

page_title: 'Wingle'
