paths:
  logo:   'loldesign_publisher/logo.svg'
  logout: '/admins/sign_out'

  menu_links:
    admins:
      name: 'Administradores'
      path: admin_admins_path
    positions:
      name: 'Cargos'
      path: admin_positions_path
    specialties:
      name: 'Especialidades'
      path: admin_specialties_path
    questionaries:
      name: 'Questionários'
      path: admin_questionaries_path
    translations:
      name: 'Textos'
      path: admin_translations_path
    terms:
      name: 'Termos'
      path: admin_terms_path
    services:
      name: 'Pacote de Serviços'
      path: admin_package_services_path
    locales:
      name: 'Localidade'
      path: admin_locales_path
    sectors:
      name: 'Setores'
      path: admin_sectors_path
    sizes:
      name: 'Portes'
      path: admin_company_sizes_path
    modes:
      name: 'Modes'
      path: admin_modes_path
    relevances:
      name: 'Relevâncias'
      path: admin_relevances_path
    areas:
      name: 'Áreas'
      path: admin_areas_path

page_title: 'Wingle'
