# -------
# Creating first admin
# -------
if Admin.count == 0
  admin = Admin.new(email: 'suporte@loldesign.com.br', password: 'loldesign2018', password_confirmation: 'loldesign2018')

  puts "---> Admin [#{admin.email}] criado com sucesso" if admin.save
end


# -------
# Creating First Country/State/City/Default Locales
# -------
if Country.count == 0
  brasil   = Country.create(name: 'Brasil')
  sp_state = State.create(name: 'São Paulo', country: brasil)
  sp_city  = City.create(name: 'São Paulo', state: sp_state)

end

if CountryLocale.count == 0
  brasil   = Country.where(name: 'Brasil').first

  CountryLocale.create(name: 'Norte', country: brasil)
  CountryLocale.create(name: 'Nordeste', country: brasil)
  CountryLocale.create(name: 'Centro-Oeste', country: brasil)
  CountryLocale.create(name: 'Sudeste', country: brasil)
  CountryLocale.create(name: 'Sul', country: brasil)
end

if CityLocale.count == 0
  sp = City.first

  CityLocale.create(name: 'Zona Leste', city: sp)
  CityLocale.create(name: 'Zona Oeste', city: sp)
  CityLocale.create(name: 'Zona Sul', city: sp)
  CityLocale.create(name: 'Zona Norte', city: sp)
  CityLocale.create(name: 'Centro', city: sp)
end

if Neighborhood.count == 0
  sp = City.first
  east   = CityLocale.find(1)
  south  = CityLocale.find(3)
  center = CityLocale.find(5)

  Neighborhood.create(name: 'Mooca', city: sp, city_locale: east)
  Neighborhood.create(name: 'Cambuci', city: sp, city_locale: center)
  Neighborhood.create(name: 'Jabaquara', city: sp, city_locale: south)
  Neighborhood.create(name: 'Sé', city: sp, city_locale: center)
  Neighborhood.create(name: 'Vila Mariana', city: sp, city_locale: south)
  Neighborhood.create(name: 'Itaim', city: sp, city_locale: south)
  Neighborhood.create(name: 'Sapopemba', city: sp, city_locale: east)
  Neighborhood.create(name: 'Morumbi', city: sp, city_locale: south)
  Neighborhood.create(name: 'Moema', city: sp, city_locale: south)
  Neighborhood.create(name: 'Interlagos', city: sp, city_locale: south)
end

# if after Oct 5, 2018 it may have 10 neighborhoods
if Neighborhood.count == 10
  sp = City.first
  east   = CityLocale.find(1)
  west   = CityLocale.find(2)
  south  = CityLocale.find(3)
  north  = CityLocale.find(4)
  center = CityLocale.find(5)

  # Update old neighborhoods
  Neighborhood.find_by_name('Mooca').update_attributes(city_locale: east)
  Neighborhood.find_by_name('Cambuci').update_attributes(city_locale: center)
  Neighborhood.find_by_name('Jabaquara').update_attributes(city_locale: south)
  Neighborhood.find_by_name('Sé').update_attributes(city_locale: center)
  Neighborhood.find_by_name('Vila Mariana').update_attributes(city_locale: south)
  Neighborhood.find_by_name('Itaim').update_attributes(city_locale: south)
  Neighborhood.find_by_name('Sapopemba').update_attributes(city_locale: east)
  Neighborhood.find_by_name('Morumbi').update_attributes(city_locale: south)
  Neighborhood.find_by_name('Moema').update_attributes(city_locale: south)
  Neighborhood.find_by_name('Interlagos').update_attributes(city_locale: south)

  # Create new neighborhoods
  # Center
  Neighborhood.create(name: 'Bela Vista', city: sp, city_locale: center)
  Neighborhood.create(name: 'Liberdade', city: sp, city_locale: center)
  Neighborhood.create(name: 'Aclimação', city: sp, city_locale: center)
  Neighborhood.create(name: 'Consolação', city: sp, city_locale: center)
  Neighborhood.create(name: 'Higienópolis', city: sp, city_locale: center)
  Neighborhood.create(name: 'Santa Cecília', city: sp, city_locale: center)
  Neighborhood.create(name: 'República', city: sp, city_locale: center)
  Neighborhood.create(name: 'Bom Retiro', city: sp, city_locale: center)
  # South
  Neighborhood.create(name: 'Jardins', city: sp, city_locale: south)
  Neighborhood.create(name: 'Paulista', city: sp, city_locale: south)
  Neighborhood.create(name: 'Berrini', city: sp, city_locale: south)
  Neighborhood.create(name: 'Vila Olímpia', city: sp, city_locale: south)
  Neighborhood.create(name: 'Brooklin', city: sp, city_locale: south)
  Neighborhood.create(name: 'Campo Belo', city: sp, city_locale: south)
  Neighborhood.create(name: 'Saúde', city: sp, city_locale: south)
  Neighborhood.create(name: 'Chác. Sto. Antônio', city: sp, city_locale: south)
  Neighborhood.create(name: 'Sto. Amaro', city: sp, city_locale: south)
  Neighborhood.create(name: 'Socorro', city: sp, city_locale: south)
  Neighborhood.create(name: 'Cidade Jardim', city: sp, city_locale: south)
  Neighborhood.create(name: 'Ipiranga', city: sp, city_locale: south)
  Neighborhood.create(name: 'Cursino', city: sp, city_locale: south)
  Neighborhood.create(name: 'Sacomã', city: sp, city_locale: south)
  Neighborhood.create(name: 'ABC e região', city: sp, city_locale: south)
  # West
  Neighborhood.create(name: 'Pinheiros', city: sp, city_locale: west)
  Neighborhood.create(name: 'Alto de Pinheiros', city: sp, city_locale: west)
  Neighborhood.create(name: 'Vila Madalena', city: sp, city_locale: west)
  Neighborhood.create(name: 'Lapa', city: sp, city_locale: west)
  Neighborhood.create(name: 'Barra Funda', city: sp, city_locale: west)
  Neighborhood.create(name: 'Perdizes', city: sp, city_locale: west)
  Neighborhood.create(name: 'Vila Leopoldina', city: sp, city_locale: west)
  Neighborhood.create(name: 'Jaguaré', city: sp, city_locale: west)
  Neighborhood.create(name: 'Butantã', city: sp, city_locale: west)
  Neighborhood.create(name: 'Vila Sônia', city: sp, city_locale: west)
  Neighborhood.create(name: 'Raposo Tavares', city: sp, city_locale: west)
  Neighborhood.create(name: 'Osasco', city: sp, city_locale: west)
  Neighborhood.create(name: 'Barueri', city: sp, city_locale: west)
  Neighborhood.create(name: 'Alphaville e região', city: sp, city_locale: west)
  Neighborhood.create(name: 'Cotia', city: sp, city_locale: west)
  Neighborhood.create(name: 'Embú', city: sp, city_locale: west)
  Neighborhood.create(name: 'Taboão e região', city: sp, city_locale: west)
  # North
  Neighborhood.create(name: 'Santana', city: sp, city_locale: north)
  Neighborhood.create(name: 'Casa Verde', city: sp, city_locale: north)
  Neighborhood.create(name: 'Vila Guilherme', city: sp, city_locale: north)
  Neighborhood.create(name: 'Vila Maria', city: sp, city_locale: north)
  Neighborhood.create(name: 'Freguesia do Ó', city: sp, city_locale: north)
  Neighborhood.create(name: 'Brasilândia', city: sp, city_locale: north)
  Neighborhood.create(name: 'Pirituba', city: sp, city_locale: north)
  Neighborhood.create(name: 'São Domingos', city: sp, city_locale: north)
  Neighborhood.create(name: 'Jaraguá', city: sp, city_locale: north)
  Neighborhood.create(name: 'Guarulhos e região', city: sp, city_locale: north)
  # East
  Neighborhood.create(name: 'Brás', city: sp, city_locale: east)
  Neighborhood.create(name: 'Pari', city: sp, city_locale: east)
  Neighborhood.create(name: 'Belém', city: sp, city_locale: east)
  Neighborhood.create(name: 'Tatuapé', city: sp, city_locale: east)
  Neighborhood.create(name: 'Água Rasa', city: sp, city_locale: east)
  Neighborhood.create(name: 'Vila Prudente', city: sp, city_locale: east)
  Neighborhood.create(name: 'São Lucas', city: sp, city_locale: east)
  Neighborhood.create(name: 'Carrão', city: sp, city_locale: east)
  Neighborhood.create(name: 'Penha', city: sp, city_locale: east)
  Neighborhood.create(name: 'Vila Formosa', city: sp, city_locale: east)
  Neighborhood.create(name: 'Aricanduva', city: sp, city_locale: east)
  Neighborhood.create(name: 'Artur Alvim', city: sp, city_locale: east)
  Neighborhood.create(name: 'Itaquera', city: sp, city_locale: east)
  Neighborhood.create(name: 'Cidade São Mateus', city: sp, city_locale: east)
end

# -------
# Creating First Sectors
# -------
if Sector.count == 0
  Sector.create(name: 'INDÚSTRIA PESADA', description: 'Metais e Mineração, Siderurgia, Construção Pesada, Máquinas e Bens de Capital')
  Sector.create(name: 'ENERGIA E RECURSOS NATURAIS', description: 'Óleo & Gás,Energias Renováveis,Combustíveis')
  Sector.create(name: 'INDÚSTRIA DE MANUFATURA', description: 'Automotiva, Aeronáutica, Naval, Ferroviária, Maquinas e Equipamentos')
  Sector.create(name: 'TRANSPORTE E LOGÍSTICA', description: 'Aéreo, Rodoviário, Marítimo, Ferroviário, Centros de Distribuição')
  Sector.create(name: 'CONSTRUÇÃO E INCORPORAÇÃO', description: 'Residencial, Comercial, Galpões Logísticos, Infraestrutura, Imobiliárias')
  Sector.create(name: 'INDÚSTRIA AGROPECUÁRIA', description: 'Frigoríficos, Tradings, Papel e Celulose, Commodities, Têxtil')
  Sector.create(name: 'INDÚSTRIA QUÍMICA', description: 'Agroquímicos, Petroquímicos, Tintas,Polímeros')
  Sector.create(name: 'INDÚSTRIA FARMACÊUTICA', description: 'Farmacêutica, Laboratórios')
  Sector.create(name: 'BENS DE CONSUMO', description: 'Higiene e Limpeza, Utilidades Domésticas, Eletro Eletrônicos, Alimentos e Bebidas, Vestuário')
  Sector.create(name: 'TI & TELECOM', description: 'Software, Hardware, Operadoras de Telefonia')
  Sector.create(name: 'INOVAÇÃO DIGITAL', description: 'E-Commerce, Marketplaces, Tech Companies, IOT, Wearable')
  Sector.create(name: 'MERCADO FINANCEIRO', description: 'Bancos, Seguradoras e Corretoras, Meios de Pagamento, Boutiques de Investimento, Serviços Financeiros')
  Sector.create(name: 'CONSULTORIAS', description: '')
  Sector.create(name: 'ESCRITÓRIOS JURÍDICOS', description: '')
  Sector.create(name: 'VAREJO & ATACADO', description: 'Mercados e Atacadistas, Shopping Center e Franquias, Varejistas, Equipamentos Domésticos, Mobília e Decoração')
  Sector.create(name: 'SERVIÇOS', description: 'Educação, Hospitais, Hotelaria e Turismo, Entretenimento, Saúde e Bem estar,etc')
  Sector.create(name: 'PUBLICADADE E PROPAGANDA', description: '')
  Sector.create(name: 'TERCEIRO SETOR', description: 'ONGs, Parceria Público Privadas, Iniciativa Privada sem fins lucrativos')
end

# -------
# Creating First Company Sizes
# -------
if CompanySize.count == 0
  CompanySize.create(name: 'INÍCIO DE OPERAÇÃO', description: 'maior autonomia, relevância e dinamismo')
  CompanySize.create(name: 'EMPRESA MÉDIA', description: 'oportunidade de crescimento e estruturação de processos')
  CompanySize.create(name: 'GRANDE CORPORAÇÃO', description: 'hierarquia, melhoria de processos e estabilidade')
end

# -------
# Creating First Modes
# -------
if Mode.count == 0
  Mode.create(name: 'AGRESSIVA', description: 'foco no curto prazo, números e performance')
  Mode.create(name: 'MODERADA', description: 'foco no médio prazo, negócio e pessoas')
  Mode.create(name: 'CONSERVADORA', description: 'foco no longo prazo, hierarquizada e tradicional')
end

# -------
# Creating First Relevances
# -------
if Relevance.count == 0
  Relevance.create(name: 'PORTE DA EMPRESA', priority: 3)
  Relevance.create(name: 'SETOR DE ATUAÇÃO', priority: 2)
  Relevance.create(name: 'LOCALIZAÇÃO', priority: 1)
end

# -------
# Creating First Areas, Functions and Habilities
# -------
if Area.count == 0
  # AREAS 01
  area_01 = Area.create(name: 'VENDAS')

  function_01 = Function.create(name: 'B2B - Engenheiro de Vendas', area: area_01)
  Hability.create(name: 'Fornecer suporte técnico de vendas', function: function_01)
  Hability.create(name: 'Desenvolver produtos ou soluções competitivas', function: function_01)
  Hability.create(name: 'Auxiliar no atingimento das metas de vendas', function: function_01)
  Hability.create(name: 'Explicar questões técnicas sobre produtos', function: function_01)
  Hability.create(name: 'Estruturar propostas comerciais', function: function_01)
  Hability.create(name: 'Suportar atividades de pré-venda', function: function_01)
  Hability.create(name: 'Analisar especificações do cliente', function: function_01)
  Hability.create(name: 'Manter relacionamento com clientes', function: function_01)

  function_02 = Function.create(name: 'B2B - Pré-vendas', area: area_01)
  Hability.create(name: 'Explicar aspectos técnicos ', function: function_02)
  Hability.create(name: 'Estruturar propostas', function: function_02)
  Hability.create(name: 'Realizar cotações', function: function_02)
  Hability.create(name: 'Visitar clientes', function: function_02)
  Hability.create(name: 'Oferecer ideas para novas soluções', function: function_02)
  Hability.create(name: 'Garantir a execução de produtos ou serviços', function: function_02)
  Hability.create(name: 'Verificar novas oportunidades em clientes recorrentes', function: function_02)

  function_03 = Function.create(name: 'B2B - Vendas Corporativas', area: area_01)
  Hability.create(name: 'Identificar empresas no mercado', function: function_03)
  Hability.create(name: 'Agendar visitas de prospecção e relacionamento', function: function_03)
  Hability.create(name: 'Entender o problema do cliente', function: function_03)
  Hability.create(name: 'Apresentar soluções de produtos ou serviços', function: function_03)
  Hability.create(name: 'Atender metas de atividade comercial', function: function_03)
  Hability.create(name: 'Representar a empresa em eventos corporativos', function: function_03)
  Hability.create(name: 'Lidar com objeções ', function: function_03)
  Hability.create(name: 'Negociar e fechar negócios com empresas', function: function_03)
  Hability.create(name: 'Captar novos clientes', function: function_03)
  Hability.create(name: 'Fazer relacionamento com clientes recorrentes', function: function_03)
  Hability.create(name: 'Resgatar clientes antigos', function: function_03)

  function_04 = Function.create(name: 'B2B - Contas Estratégicas', area: area_01)
  Hability.create(name: 'Fidelizar portifolio de clientes', function: function_04)
  Hability.create(name: 'Entender as necessidades dos clientes', function: function_04)
  Hability.create(name: 'Expandir o leque de soluções por cliente', function: function_04)
  Hability.create(name: 'Garantir que produtos e serviços sejam executados no prazo', function: function_04)
  Hability.create(name: 'Facilitar a comunicação entre clientes e equipes internas', function: function_04)
  Hability.create(name: 'Lidar com reclamações e oferecer soluções', function: function_04)
  Hability.create(name: 'Preparar relatórios com métricas das contas', function: function_04)

  function_05 = Function.create(name: 'B2B - Desenvolvimento de Negócios', area: area_01)
  Hability.create(name: 'Desenvolver estratégias e planos de crescimento', function: function_05)
  Hability.create(name: 'Trabalhar ações de retenção para clientes existentes', function: function_05)
  Hability.create(name: 'Aumentar base de clientes', function: function_05)
  Hability.create(name: 'Trasmitir a proposta de valor do s produtos e serviços', function: function_05)
  Hability.create(name: 'Negociar com partes interessadas', function: function_05)
  Hability.create(name: 'Mapear necessidades e tendências de mercado', function: function_05)
  Hability.create(name: 'Elaborar e revisar contratos', function: function_05)
  Hability.create(name: 'Identificar oportunidades para ações e campanhas', function: function_05)

  function_06 = Function.create(name: 'B2B - Canais e Alianças', area: area_01)
  Hability.create(name: 'Desenvolver parceiros de canal em territórios', function: function_06)
  Hability.create(name: 'Gerenciar receitas de vendas por região', function: function_06)
  Hability.create(name: 'Executar plano de negócios para atingimento de metas', function: function_06)
  Hability.create(name: 'Analisar tendências do mercado', function: function_06)
  Hability.create(name: 'Desenvolver planos de venda', function: function_06)
  Hability.create(name: 'Educar parceiros sobre portifolio de produtos ou serviços', function: function_06)
  Hability.create(name: 'Resolver problemas relacionados a parceiros', function: function_06)
  Hability.create(name: 'Suportar parceiros com iniciativas de marketing local', function: function_06)

  function_07 = Function.create(name: 'B2B - Expansão de Rede ', area: area_01)
  Hability.create(name: 'Coloborar com a estratégia da expansão da rede', function: function_07)
  Hability.create(name: 'Participar de feiras e eventos', function: function_07)
  Hability.create(name: 'Prospecção de novos franqueados', function: function_07)
  Hability.create(name: 'Triagem e entrevista de franqueados', function: function_07)
  Hability.create(name: 'Apresentação do modelo de franquia', function: function_07)
  Hability.create(name: 'Negociação e fechamento', function: function_07)
  Hability.create(name: 'Sugerir localização das unidades', function: function_07)

  function_08 = Function.create(name: 'B2C - Distribuição para Varejo', area: area_01)
  Hability.create(name: 'Fornececer informações do produto ou serviço', function: function_08)
  Hability.create(name: 'Realizar comparações de preço ', function: function_08)
  Hability.create(name: 'Assegurar prateiras cheias nos pontos de venda', function: function_08)
  Hability.create(name: 'Gerenciar devoluções de mercadorias', function: function_08)
  Hability.create(name: 'Informar clientes sobre descontos e ofertas', function: function_08)
  Hability.create(name: 'Responder pergunta dos clientes sobre produtos', function: function_08)

  function_09 = Function.create(name: 'B2C - Venda Direta ', area: area_01)
  Hability.create(name: 'Visitar potenciais consumidores', function: function_09)
  Hability.create(name: 'Apresentar produtos ou serviços', function: function_09)
  Hability.create(name: 'Esclarecer dúvidas ', function: function_09)
  Hability.create(name: 'Executar pedidos de compra', function: function_09)
  Hability.create(name: 'Negociar preços', function: function_09)
  Hability.create(name: 'Falar com matriz e filiais', function: function_09)
  Hability.create(name: 'Emitir propostas comerciais', function: function_09)
  Hability.create(name: 'Manter cadastros atualizados', function: function_09)
  Hability.create(name: 'Elaborar relatórios de vendas', function: function_09)

  function_10 = Function.create(name: 'Call Center', area: area_01)
  Hability.create(name: 'Analisar métricas de atendimento ao cliente', function: function_10)
  Hability.create(name: 'Dimensionar a equipe de atendimento', function: function_10)
  Hability.create(name: 'Gerir e treinar a equipe de atendimento', function: function_10)
  Hability.create(name: 'Controlar despesas', function: function_10)
  Hability.create(name: 'Preparar relatórios gerenciais', function: function_10)
  Hability.create(name: 'Experiência com call center ativo', function: function_10)
  Hability.create(name: 'Experiência com call center receptivo', function: function_10)
  Hability.create(name: 'Resolver problemas críticos de atendimento', function: function_10)

  # AREA 02
  area_02 = Area.create(name: 'Marketing & Comunicação')

  function_12 = Function.create(name: 'Inovação', area: area_02)
  Hability.create(name: 'Criação de novos produtos ou serviços', function: function_12)
  Hability.create(name: 'Desenvolvimento de protótipos', function: function_12)
  Hability.create(name: 'Análise de tendências de mercado', function: function_12)
  Hability.create(name: 'Estratégia de inovação', function: function_12)
  Hability.create(name: 'Envolvimento com áreas chave', function: function_12)
  Hability.create(name: 'Projetos Nacionais', function: function_12)
  Hability.create(name: 'Projetos Internacionais', function: function_12)
  Hability.create(name: 'Envolvimento com alta gestão', function: function_12)
  Hability.create(name: 'Novas patentes', function: function_12)
  Hability.create(name: 'Gestão de KPIs', function: function_12)
  Hability.create(name: 'Foco em B2B', function: function_12)
  Hability.create(name: 'Foco em B2C', function: function_12)
  Hability.create(name: 'Foco em C2C', function: function_12)

  function_13 = Function.create(name: 'Marca & Branding', area: area_02)
  Hability.create(name: 'Analisar como a marca está posicionada no mercado', function: function_13)
  Hability.create(name: 'Concretizar a visão, missão e objetivos da marca', function: function_13)
  Hability.create(name: 'Definir planos de marca e estratégias de mercado', function: function_13)
  Hability.create(name: 'Liderar o engajamento interno', function: function_13)
  Hability.create(name: 'Medir o desempenho e o retorno de campanhas (ROI e KPIs)', function: function_13)
  Hability.create(name: 'Treinar a equipe', function: function_13)
  Hability.create(name: 'Supervisionar marketing e publicidade para garantir fidelidade', function: function_13)
  Hability.create(name: 'Monitorar distribuição do produto e reação do consumidor', function: function_13)
  Hability.create(name: 'Alinhar a empresa em torno da direção, escolha e táticas da marca', function: function_13)
  Hability.create(name: 'Foco em B2B', function: function_13)
  Hability.create(name: 'Foco em B2C', function: function_13)
  Hability.create(name: 'Foco em C2C', function: function_13)

  function_14 = Function.create(name: 'Produto & Categoria', area: area_02)
  Hability.create(name: 'Visão e estratégia do produto', function: function_14)
  Hability.create(name: 'Acompanhar as revisões de categoria de varejo', function: function_14)
  Hability.create(name: 'Executar programas promocionais', function: function_14)
  Hability.create(name: 'Melhorar a rentabilidade dos programas', function: function_14)
  Hability.create(name: 'Contribuir com o lançamento de novos itens', function: function_14)
  Hability.create(name: 'Análise de inventário e ciclo de produtos', function: function_14)
  Hability.create(name: 'Colaboração entre estoque e planejamento de vendas', function: function_14)

  function_15 = Function.create(name: 'Trade Marketing', area: area_02)
  Hability.create(name: 'Desenvolver e criar programas', function: function_15)
  Hability.create(name: 'Contribuir para atingir metas de vendas', function: function_15)
  Hability.create(name: 'Melhorar a participação no mercado', function: function_15)
  Hability.create(name: 'Estabelecer estratégias com envolvidos', function: function_15)
  Hability.create(name: 'Preparar plano promocional', function: function_15)
  Hability.create(name: 'Estabelecer a estratégia de marketing no ponto de vendas', function: function_15)
  Hability.create(name: 'Verificar oportunidade de negócios', function: function_15)
  Hability.create(name: 'Liderar equipe de promotores', function: function_15)

  function_16 = Function.create(name: 'Planejamento Estratégico (FIN)', area: area_02)
  Hability.create(name: 'Modelar a estratégia e missão da empresa', function: function_16)
  Hability.create(name: 'Desenvolver planos de negócio', function: function_16)
  Hability.create(name: 'Avaliar ameaças e oportunidades', function: function_16)
  Hability.create(name: 'Analisar desempenho operacional da empresa', function: function_16)
  Hability.create(name: 'Alinhar recursos e metas de departamento com estratégia geral', function: function_16)
  Hability.create(name: 'Suportar mudanças organizacionais', function: function_16)
  Hability.create(name: 'Orientar liderança na tomada de decisões eficazes', function: function_16)
  Hability.create(name: 'Monitorar tendências do setor e mudanças do mercado', function: function_16)
  Hability.create(name: 'Foco em B2B', function: function_16)
  Hability.create(name: 'Foco em B2C', function: function_16)
  Hability.create(name: 'Foco em C2C', function: function_16)

  function_17 = Function.create(name: 'Inteligência de mercado (TI?)', area: area_02)
  Hability.create(name: 'Preparar budget e alocação de recursos', function: function_17)
  Hability.create(name: 'Realizar pesquisas de mercado', function: function_17)
  Hability.create(name: 'Determinar oportunidades e tendências', function: function_17)
  Hability.create(name: 'Avaliar ameaças no mercado', function: function_17)
  Hability.create(name: 'Fornecer informações para o planejamento estratégico', function: function_17)
  Hability.create(name: 'Revisar a segmentação de clientes', function: function_17)
  Hability.create(name: 'Analisar informações de mercado por amostra', function: function_17)
  Hability.create(name: 'Monitorar análises e métricas para o negócio', function: function_17)
  Hability.create(name: 'Relatórios gerenteciais', function: function_17)
  Hability.create(name: 'Foco em B2B', function: function_17)
  Hability.create(name: 'Foco em B2C', function: function_17)
  Hability.create(name: 'Foco em C2C', function: function_17)

  function_18 = Function.create(name: 'Marketing e Comunicação', area: area_02)
  Hability.create(name: 'Criar planos para aumentar participação no mercado', function: function_18)
  Hability.create(name: 'Realizar e analisar pesquisas de mercado', function: function_18)
  Hability.create(name: 'Desenvolver estratégias de precificação', function: function_18)
  Hability.create(name: 'Produzir materiais promocionais e conteúdo para suporte', function: function_18)
  Hability.create(name: 'Relacionamento com parceiros de agências', function: function_18)
  Hability.create(name: 'Criar apresentações de marketing', function: function_18)
  Hability.create(name: 'Desenvolver cronogramas com ações', function: function_18)
  Hability.create(name: 'Realizar eventos com clientes', function: function_18)
  Hability.create(name: 'Medir performance de campanhas', function: function_18)
  Hability.create(name: 'Produzir conteúdo para Blog e Website', function: function_18)
  Hability.create(name: 'Criar e promover campanhas', function: function_18)
  Hability.create(name: 'Foco em B2B', function: function_18)
  Hability.create(name: 'Foco em B2C', function: function_18)
  Hability.create(name: 'Foco em C2C', function: function_18)

  function_19 = Function.create(name: 'Relações Públicas', area: area_02)
  Hability.create(name: 'Responsabilidade Social', function: function_19)
  Hability.create(name: 'Produzir  press releases', function: function_19)
  Hability.create(name: 'Lidar com perguntas do público', function: function_19)
  Hability.create(name: 'Participar de conferências de imprensa', function: function_19)
  Hability.create(name: 'Analisar cobertura da mídia', function: function_19)
  Hability.create(name: 'Realizar pesquisa de mercado', function: function_19)
  Hability.create(name: 'Zelar pea imagem da empresa', function: function_19)
  Hability.create(name: 'Proteger a imagem de executivos', function: function_19)

  function_20 = Function.create(name: 'Media Planner', area: area_02)
  Hability.create(name: 'Trabalhar o funil de vendas', function: function_20)
  Hability.create(name: 'Realização de pesquisas', function: function_20)
  Hability.create(name: 'Análise de dados de clientes', function: function_20)
  Hability.create(name: 'Relacioanmento com fornecedores', function: function_20)
  Hability.create(name: 'Gerenciamento de mídias Sociais', function: function_20)
  Hability.create(name: 'Campanhas na TV, Rádio e Internet', function: function_20)
  Hability.create(name: 'Criação de campanhas e conteúdo', function: function_20)
  Hability.create(name: 'Elaboração do desing gráfico', function: function_20)
  Hability.create(name: 'Foco em B2B', function: function_20)
  Hability.create(name: 'Foco em B2C', function: function_20)
  Hability.create(name: 'Foco em C2C', function: function_20)

  function_20 = Function.create(name: 'Eventos', area: area_02)
  Hability.create(name: 'Organização de eventos', function: function_20)
  Hability.create(name: 'Controle do orçamento', function: function_20)
  Hability.create(name: 'Avaliação de fornecedores', function: function_20)
  Hability.create(name: 'Acompanhar montagem e desmontagem', function: function_20)
  Hability.create(name: 'Organizar logística dos participantes', function: function_20)
  Hability.create(name: 'Foco em B2B', function: function_20)
  Hability.create(name: 'Foco em B2C', function: function_20)
  Hability.create(name: 'Foco em C2C', function: function_20)

  function_21 = Function.create(name: 'Customer Service', area: area_02)
  Hability.create(name: 'Resolver problemas de clientes', function: function_21)
  Hability.create(name: 'Determinar a causa do problema', function: function_21)
  Hability.create(name: 'Garantir a resolução', function: function_21)
  Hability.create(name: 'Preparar relatórios de acompanhamento', function: function_21)
  Hability.create(name: 'Avaliar as necessidades dos clientes para alcançar a satisfação', function: function_21)
  Hability.create(name: 'Resolver reclamações de clientes via telefone, email, email ou mídias sociais', function: function_21)
  Hability.create(name: 'Foco no produto', function: function_21)
  Hability.create(name: 'Foco em serviços', function: function_21)

  function_22 = Function.create(name: 'Digital Marketing', area: area_02)
  Hability.create(name: 'Planejar e executar todo marketing digital', function: function_22)
  Hability.create(name: 'Gerenciar mídias sociais', function: function_22)
  Hability.create(name: 'Revisar SEO e SEM', function: function_22)
  Hability.create(name: 'Avaliar indicadores e realizar análises', function: function_22)
  Hability.create(name: 'Controlar orçamento e entender ROI', function: function_22)
  Hability.create(name: 'Colaborar com agências e terceiros', function: function_22)
  Hability.create(name: 'Produzir e divulgar conteúdo', function: function_22)
  Hability.create(name: 'Captar leads de potenciais clientes', function: function_22)

  function_23 = Function.create(name: 'CRM', area: area_02)
  Hability.create(name: 'Estratégia de retenção e fidelização de clientes', function: function_23)
  Hability.create(name: 'Estruturar funil de vendas', function: function_23)
  Hability.create(name: 'Segmentar o banco de dados corretamente', function: function_23)
  Hability.create(name: 'Definir a estratégia em conjunto com outras áreas', function: function_23)
  Hability.create(name: 'Medir e analisar resultados', function: function_23)
  Hability.create(name: 'Propor abordagens mais eficientes', function: function_23)
  Hability.create(name: 'Lidar com fornecedores', function: function_23)
  Hability.create(name: 'Foco em B2B', function: function_23)
  Hability.create(name: 'Foco em B2C', function: function_23)
  Hability.create(name: 'Foco em C2C', function: function_23)

  function_24 = Function.create(name: 'Revenue & Pricing', area: area_02)
  Hability.create(name: 'Avaliação das estratégias de preço', function: function_24)
  Hability.create(name: 'Posicionamento de marca', function: function_24)
  Hability.create(name: 'Análise da concorrência', function: function_24)
  Hability.create(name: 'Tendências de mercado', function: function_24)
  Hability.create(name: 'Custo de Produção', function: function_24)
  Hability.create(name: 'Análise de margem', function: function_24)
  Hability.create(name: 'Relatórios gerenciais', function: function_24)
  Hability.create(name: 'Cadastro de precos e descontos', function: function_24)
  Hability.create(name: 'Definição de promoções', function: function_24)
  Hability.create(name: 'Foco em B2B', function: function_24)
  Hability.create(name: 'Foco em B2C', function: function_24)
  Hability.create(name: 'Foco em C2C', function: function_24)

  # AREA 03
  area_03 = Area.create(name: 'Suprimentos, Compras & Logística')

  function_25 = Function.create(name: 'Comércio Exterior', area: area_03)
  Hability.create(name: 'Importação', function: function_25)
  Hability.create(name: 'Exportação', function: function_25)
  Hability.create(name: 'Importação e Exportação', function: function_25)
  Hability.create(name: 'Tranporte Áereo ', function: function_25)
  Hability.create(name: 'Transporte Marítimo', function: function_25)
  Hability.create(name: 'Transporte Rodoviário', function: function_25)
  Hability.create(name: 'Transporte Ferroviário', function: function_25)
  Hability.create(name: 'Desembaraço aduaneiro', function: function_25)
  Hability.create(name: 'América do Norte', function: function_25)
  Hability.create(name: 'América Latina', function: function_25)
  Hability.create(name: 'Europa', function: function_25)
  Hability.create(name: 'Ásia', function: function_25)
  Hability.create(name: 'África', function: function_25)
  Hability.create(name: 'Oceania', function: function_25)

  function_26 = Function.create(name: 'Logística, PCP e Estoque', area: area_03)
  Hability.create(name: 'Gerenciamento estratégico da logística', function: function_26)
  Hability.create(name: 'Priorização de pedidos para clientes', function: function_26)
  Hability.create(name: 'Analisar KPIs de fornecedores', function: function_26)
  Hability.create(name: 'Planejamento e controle da produção', function: function_26)
  Hability.create(name: 'Gerenciamento do estoque', function: function_26)
  Hability.create(name: 'Analisar política de sortimento', function: function_26)
  Hability.create(name: 'Catalogar mercadorias, planejar rotas e processar remessas', function: function_26)
  Hability.create(name: 'Realizar a gestão da frota', function: function_26)

  function_27 = Function.create(name: 'Compras', area: area_03)
  Hability.create(name: 'Desenvolver estratégia de compras', function: function_27)
  Hability.create(name: 'Acompanhar métricas e reduzir despezas', function: function_27)
  Hability.create(name: 'Realizar previsão de preço e tendência de mercado', function: function_27)
  Hability.create(name: 'Realizar análise de custos, cenários e benchmarking', function: function_27)
  Hability.create(name: 'Relacionamento com fornecedores estratégicos', function: function_27)
  Hability.create(name: 'Desenvolvimento de novos fornecedores', function: function_27)
  Hability.create(name: 'Avaliar, gerenciar e mitigar riscos', function: function_27)
  Hability.create(name: 'Compra de matéria prima', function: function_27)
  Hability.create(name: 'Compra de equipamentos', function: function_27)
  Hability.create(name: 'Compra de serviços', function: function_27)
  Hability.create(name: 'Compra de mercadorias', function: function_27)
  Hability.create(name: 'Compras de material de escritório', function: function_27)
  Hability.create(name: 'Atuação nacional', function: function_27)
  Hability.create(name: 'Atuação internacional', function: function_27)

  function_28 = Function.create(name: 'Supply Chain', area: area_03)
  Hability.create(name: 'Planejar e implementar a estratégia geral da cadeia de suprimentos', function: function_28)
  Hability.create(name: 'Colaborar com equipes de vendas, operações e atendimento ao cliente', function: function_28)
  Hability.create(name: 'Determinar principais KPIs da cadeia de fornecimento', function: function_28)
  Hability.create(name: 'Sugerir solulções para melhorias de processo', function: function_28)
  Hability.create(name: 'Identificar gargalos e implementar soluções', function: function_28)
  Hability.create(name: 'Trabalhar com vendas e finanças na escolha de fornecedores', function: function_28)
  Hability.create(name: 'Atuação nacional', function: function_28)
  Hability.create(name: 'Atuação internacional', function: function_28)

  # AREA 04
  area_04 = Area.create(name: 'Engenharia & Produção')

  function_29 = Function.create(name: 'Operações', area: area_04)
  Hability.create(name: 'Entregar a produção nas metas estabelecidas', function: function_29)
  Hability.create(name: 'Melhorar sistemas operacionais continuamente', function: function_29)
  Hability.create(name: 'Programar a necessidade de insumos produtivos', function: function_29)
  Hability.create(name: 'Avaliar e melhorar KPIs de produção', function: function_29)
  Hability.create(name: 'Realizar controle de qualidade', function: function_29)
  Hability.create(name: 'Alocar recursos de forma eficaz', function: function_29)
  Hability.create(name: 'Analisar dados para reduzir disperdício', function: function_29)
  Hability.create(name: 'Gerenciar turnos e horas extras', function: function_29)
  Hability.create(name: 'Abordar questões ou queixas de funcionários', function: function_29)
  Hability.create(name: 'Administrar acordos coletivos de trabalho', function: function_29)

  function_30 = Function.create(name: 'Saúde, Segurança e Meior Ambiente', area: area_04)
  Hability.create(name: 'Desenvolver programas de treinamento de segurança ', function: function_30)
  Hability.create(name: 'Manter os regulamentos de segurança em conformidade', function: function_30)
  Hability.create(name: 'Inspecionar todos os equipamentos de proteção', function: function_30)
  Hability.create(name: 'Supervisionar e gerenciar todos os resíduos perigosos', function: function_30)
  Hability.create(name: 'Avaliar todas as licenças ambientais necessárias', function: function_30)
  Hability.create(name: 'Recomendar melhorias para os sistemas de gestão da qualidade', function: function_30)
  Hability.create(name: 'Implementar soluções em situações emergenciais', function: function_30)
  Hability.create(name: 'Atender todas as políticas de órgãos reguladores', function: function_30)
  Hability.create(name: 'Recomendar estratégias para redução de acidentes', function: function_30)
  Hability.create(name: 'Monitorar programas de proteção e conservação', function: function_30)

  function_31 = Function.create(name: 'Produção & Processos', area: area_04)
  Hability.create(name: 'Planejar e coordenar processos de engenharia de produção', function: function_31)
  Hability.create(name: 'Produzir produtos que atendam padrões de qualidade', function: function_31)
  Hability.create(name: 'Desenvolver melhorias de processos', function: function_31)
  Hability.create(name: 'Desenvolver estratégias operacionais para atingir metas financeiras', function: function_31)
  Hability.create(name: 'Desenvolver estratégias para atingir metas de produção', function: function_31)
  Hability.create(name: 'Identificar operações e práticas inseguras', function: function_31)
  Hability.create(name: 'Realizar análises para reduzir tempo de inativadade e interrupções', function: function_31)
  Hability.create(name: 'Implementar iniciativas de redução de custos', function: function_31)
  Hability.create(name: 'Fornecer treinamento e orientação para membros da equipe', function: function_31)
  Hability.create(name: 'Compartilhar melhores práticas', function: function_31)
  Hability.create(name: 'Auxiliar na preparação do orçamento e monitorar despesas', function: function_31)

  function_32 = Function.create(name: 'Desenvolvimento de Produtos', area: area_04)
  Hability.create(name: 'Desenvolver  protótipos de projetos', function: function_32)
  Hability.create(name: 'Realizar testes e avaliar funcionalidades', function: function_32)
  Hability.create(name: 'Analisar novos componentes, materiais e tecnologias', function: function_32)
  Hability.create(name: 'Coordenar equipes multidisciplinares', function: function_32)
  Hability.create(name: 'Promover iniciativas contínuas de melhorias de produtos', function: function_32)
  Hability.create(name: 'Elaborar cronogramas para implementação efetiva de projetos', function: function_32)
  Hability.create(name: 'Calcular o custo do produto', function: function_32)
  Hability.create(name: 'Atender questões regulatórias internas e externas', function: function_32)
  Hability.create(name: 'Aprovar protótipos que atendam critérios de qualidade da empresa', function: function_32)
  Hability.create(name: 'Desenvolver ou selecionar equipamentos para a execução de testes', function: function_32)
  Hability.create(name: 'Registrar e documentar os resultados', function: function_32)

  function_33 = Function.create(name: 'Manutenção e Facilities', area: area_04)
  Hability.create(name: 'Realizar manutenção preditiva e preventiva', function: function_33)
  Hability.create(name: 'Inspecionar instalações para verificar e resolver problemas', function: function_33)
  Hability.create(name: 'Verificar sistemas elétricos e hidráulicos', function: function_33)
  Hability.create(name: 'Supervisionar atividades de reparo e instalação', function: function_33)
  Hability.create(name: 'Monitorar o estoque de equipamentos', function: function_33)
  Hability.create(name: 'Lidar com serviços terceirizados', function: function_33)
  Hability.create(name: 'Monitorar despesas e controle do orçamento', function: function_33)
  Hability.create(name: 'Manter registros de manutenção e relatar atividades', function: function_33)
  Hability.create(name: 'Garantir que as políticas de saúde e segurança sejam cumpridas', function: function_33)

  function_34 = Function.create(name: 'Controle e Automação', area: area_04)
  Hability.create(name: 'Gerir processos eletromecânicos', function: function_34)
  Hability.create(name: 'Supervisionar processos de controles computacionais para fabricação', function: function_34)
  Hability.create(name: 'Integrar sistemas elétricos e mecânicos na manutafura', function: function_34)
  Hability.create(name: 'Realizar testes e documentar sistemas eletromecânicos', function: function_34)
  Hability.create(name: 'Fabricar novos equipamentos para produção', function: function_34)
  Hability.create(name: 'Desenvolver soluções de produção para novas linhas de produtos', function: function_34)
  Hability.create(name: 'Testar e validar dispositivos', function: function_34)
  Hability.create(name: 'Prototipar dispositivos mecatrônicos', function: function_34)
  Hability.create(name: 'Projetar motores, solenóides, sensores, circuito impresso', function: function_34)

  function_35 = Function.create(name: 'Eletricista ou Eletrônico', area: area_04)
  Hability.create(name: 'Desenvolver circuitos e dispositivos', function: function_35)
  Hability.create(name: 'Realizar melhorias em equipamentos eletrônicos', function: function_35)
  Hability.create(name: 'Garantir o funcionamento do produto', function: function_35)
  Hability.create(name: 'Projetar módulos eletrônicos customizados', function: function_35)
  Hability.create(name: 'Elaborar manuais de instruções do procedimento de teste', function: function_35)
  Hability.create(name: 'Revisar e validar projetos', function: function_35)
  Hability.create(name: 'Resolver e mitigar problemas eletrônicos', function: function_35)

  function_36 = Function.create(name: 'Mecânico', area: area_04)
  Hability.create(name: 'Desenvolver produtos', function: function_36)
  Hability.create(name: 'Projetar sistemas e componentes', function: function_36)
  Hability.create(name: 'Realizar testes e analisar resultados', function: function_36)
  Hability.create(name: 'Avaliar a qualidade do produto final', function: function_36)
  Hability.create(name: 'Elaborar orçamento e escopo de projetos', function: function_36)
  Hability.create(name: 'Preparar relatórios e documentação do produto', function: function_36)
  Hability.create(name: 'Desenvolver novas teorias ou métodos', function: function_36)
  Hability.create(name: 'Projetar e construir ferramentas', function: function_36)
  Hability.create(name: 'Projetar e construir máquinas', function: function_36)

  function_37 = Function.create(name: 'Químico', area: area_04)
  Hability.create(name: 'Analisar responsabilidade sócio ambiental em novos produtos', function: function_37)
  Hability.create(name: 'Otimizar processos industriais', function: function_37)
  Hability.create(name: 'Solucionar problemas de qualidade e segurança', function: function_37)
  Hability.create(name: 'Investigar problemas operacionais', function: function_37)
  Hability.create(name: 'Verificar segurança dos equipamentos', function: function_37)
  Hability.create(name: 'Projetar plantas químicas', function: function_37)
  Hability.create(name: 'Corrigir gargalos de processo', function: function_37)
  Hability.create(name: 'Lidar com fornecedores e serviços terceirizados', function: function_37)
  Hability.create(name: 'Coordenar pesquisas de desenvolvimento', function: function_37)
  Hability.create(name: 'Identificar oportunidades de redução de custo', function: function_37)

  function_38 = Function.create(name: 'Aplicação', area: area_04)
  Hability.create(name: 'Suportar clientes em soluções de produtos', function: function_38)
  Hability.create(name: 'Fornecer suporte pós-venda aos clientes', function: function_38)
  Hability.create(name: 'Realizar testes para qualificação do produto', function: function_38)
  Hability.create(name: 'Propor melhorias no produto', function: function_38)
  Hability.create(name: 'Coloborar com departamentos de vendas e marketing', function: function_38)
  Hability.create(name: 'Manter documentações sobre soluções de problemas', function: function_38)

  function_47 = Function.create(name: 'Alimentos', area: area_04)
  Hability.create(name: 'Qualificação dos insumos', function: function_39)
  Hability.create(name: 'Desenvolvimento de embralagens', function: function_39)
  Hability.create(name: 'Criar produtos alimentícios', function: function_39)
  Hability.create(name: 'Controlar qualidade dos produtos', function: function_39)
  Hability.create(name: 'Melhorar processos produtivos', function: function_39)
  Hability.create(name: 'Melhorar produtos existentes', function: function_39)
  Hability.create(name: 'Reduzir custos produtivos', function: function_39)

  function_40 = Function.create(name: 'Gerenciamento de Projetos', area: area_04)
  Hability.create(name: 'Garantir projetos dentro do prazo e escopo', function: function_40)
  Hability.create(name: 'Disponibilizar e alocar recursos internos e terceiros', function: function_40)
  Hability.create(name: 'Gerenciar o orçamento do projeto', function: function_40)
  Hability.create(name: 'Allinhar partes interessadas para garantir viabilidade técnica', function: function_40)
  Hability.create(name: 'Acompanhar custos e orçamento do projeto', function: function_40)
  Hability.create(name: 'Medir desempenho do projeto por métricas', function: function_40)
  Hability.create(name: 'Minimizar riscos ao projeto', function: function_40)
  Hability.create(name: 'Documentar plano e atividades', function: function_40)

  # AREA 05
  area_05 = Area.create(name: 'Finanças & Tributário')

  function_41 = Function.create(name: 'Crédito & Cobrança', area: area_05)
  Hability.create(name: 'Monitorar contas para identificar dívidas pendentes', function: function_41)
  Hability.create(name: 'Investigar dados históricos para cada dívida ou fatura', function: function_41)
  Hability.create(name: 'Entrar em contato com clientes para perguntar sobre pagamentos atrasados', function: function_41)
  Hability.create(name: 'Tomar ações para o pagamento da dívida', function: function_41)
  Hability.create(name: 'Processar pagamentos e reembolsos', function: function_41)
  Hability.create(name: 'Resolver problemas de faturamento e crédito ao cliente', function: function_41)
  Hability.create(name: 'Atualizar relatórios de cobrança e situação do contas a receber', function: function_41)

  function_42 = Function.create(name: 'Tributário', area: area_05)
  Hability.create(name: 'Executar rotinas fiscais em acordo com a legislação', function: function_42)
  Hability.create(name: 'Estruturar o planejamento tributário', function: function_42)
  Hability.create(name: 'Analisar operações tributárias complexas', function: function_42)
  Hability.create(name: 'Identificar e reduzir riscos fiscais', function: function_42)
  Hability.create(name: 'Gerenciar provisão fiscal e o processo de conformidade fiscal', function: function_42)
  Hability.create(name: 'Suportar auditorias fiscais', function: function_42)
  Hability.create(name: 'Suportar a conciliação contábil', function: function_42)
  Hability.create(name: 'Responsabilidade por tributos diretos', function: function_42)
  Hability.create(name: 'Resposabilidade por tributos indiretos', function: function_42)

  function_43 = Function.create(name: 'Controller & Controladoria', area: area_05)
  Hability.create(name: 'Autação Regional', function: function_43)
  Hability.create(name: 'Atuação em Planta Fabril', function: function_43)
  Hability.create(name: 'Atuação em Unidade de Negócio', function: function_43)
  Hability.create(name: 'Gerenciar operações contábeis', function: function_43)
  Hability.create(name: 'Gerenciar operações de tesouraria', function: function_43)
  Hability.create(name: 'Gerenciar contabilidde de custos', function: function_43)
  Hability.create(name: 'Gerenciar contabilidade de estoque', function: function_43)
  Hability.create(name: 'Reconhecimento de receitas', function: function_43)
  Hability.create(name: 'Dirigir a preparação do orçamento', function: function_43)
  Hability.create(name: 'Relatar variações entre real e orçado', function: function_43)
  Hability.create(name: 'Preparar relatórios para demonstrações financeiras', function: function_43)
  Hability.create(name: 'Cumprir exigências de relatórios do governo e declarações fiscais', function: function_43)
  Hability.create(name: 'Fortalecer controles internos', function: function_43)
  Hability.create(name: 'Conhecimento em USGAAP', function: function_43)
  Hability.create(name: 'Conhecimento em IFRS', function: function_43)

  function_44 = Function.create(name: 'Contabilidade', area: area_05)
  Hability.create(name: "Gerenciar funções contábeis", function: function_44)
  Hability.create(name: "Desenvolver relatórios contábeis", function: function_44)
  Hability.create(name: "Realizar a reconcilização de contas", function: function_44)
  Hability.create(name: "Monitorar contas a pagar, receber, e outros registros", function: function_44)
  Hability.create(name: "Criar ferramentas de gerenciamento para monitorar processos contábeis", function: function_44)
  Hability.create(name: "Auxiliar na preparação do balanço e orçamento", function: function_44)
  Hability.create(name: "Acompanhar orçamentos para departamentos, projetos e concessões", function: function_44)
  Hability.create(name: "Gerenciar o fechamento contábil", function: function_44)
  Hability.create(name: "Realizar consolidação de balanços", function: function_44)
  Hability.create(name: "Atualizar o balanço patrimonial", function: function_44)
  Hability.create(name: "Suportar auditoria interna", function: function_44)

  function_45 = Function.create(name: 'Administrativo Financeiro', area: area_05)
  Hability.create(name: "Gerenciar atividades administrativas para atingir metas financeiras", function: function_45)
  Hability.create(name: "Desenvolver cronograma e orçamento para projetos financeiros", function: function_45)
  Hability.create(name: "Monitarar as despesas do orçamento alocado", function: function_45)
  Hability.create(name: "Desenvolver e manter procedimentos administrativos", function: function_45)
  Hability.create(name: "Contribuir na preparação do plano de negócios e orçamento operacional", function: function_45)
  Hability.create(name: "Revisar faturas e realizar pagamentos ", function: function_45)
  Hability.create(name: "Analisar discrepâncias contábeis e recomendar ações corretivas", function: function_45)
  Hability.create(name: "Implementar políticas contábeis padrão", function: function_45)
  Hability.create(name: "Manutenção dos registros financeiros", function: function_45)
  Hability.create(name: "Preparação de todos os relatórios financeiros", function: function_45)
  Hability.create(name: "Gerenciar processamento de folha de pagamento e declaração de impostos", function: function_45)

  function_46 = Function.create(name: 'Tesouraria', area: area_05)
  Hability.create(name: "Analisar propostas de serviços bancários e financeiros", function: function_46)
  Hability.create(name: "Fornecer posição de caixa diária, estimativa e análise", function: function_46)
  Hability.create(name: "Apresentar caixa mensal para confeção de relatórios contábeis", function: function_46)
  Hability.create(name: "Gerenciar cartão corportativo e reembolsos para despesas", function: function_46)
  Hability.create(name: "Gerenciar linhas de crédiito, cartas de crédito e garantias corporativas", function: function_46)
  Hability.create(name: "Auxiliar departamentos fiscais e jurídicos e, transações ", function: function_46)
  Hability.create(name: "Desenvolver, monitorar e atualizar o orçamento do departamento", function: function_46)
  Hability.create(name: "Gerenciar contas a pagar e contas a receber", function: function_46)
  Hability.create(name: "Captar linhas de crédito", function: function_46)
  Hability.create(name: "Obter financiamento para importação e exportação", function: function_46)
  Hability.create(name: "Gerenciar operações com câmbio", function: function_46)
  Hability.create(name: "Gerenciar operações com commodities", function: function_46)
  Hability.create(name: "Gerenciar operações com renda variável", function: function_46)
  Hability.create(name: "Gerenciar operações com derivativos", function: function_46)

  function_47 = Function.create(name: 'Novos Negócios', area: area_05)
  Hability.create(name: "Realizar modelagem fianceira", function: function_47)
  Hability.create(name: "Verificar Due Diligence de riscos", function: function_47)
  Hability.create(name: "Visualizar oportunidades no mercado", function: function_47)
  Hability.create(name: "Suporte para decisões estratégicas da empresa", function: function_47)
  Hability.create(name: "Análise de ativos e recursos passivos", function: function_47)
  Hability.create(name: "Relacionamento com bancos", function: function_47)
  Hability.create(name: "Relacionamento com consultorias estratégicas", function: function_47)
  Hability.create(name: "Estruturação de Financimento com bancos", function: function_47)
  Hability.create(name: "Experiência com Fusões e Aquisições", function: function_47)

  function_48 = Function.create(name: 'Planejamento Financeiro', area: area_05)
  Hability.create(name: "Analisar receita, custo, despesas e ganhos de capital", function: function_48)
  Hability.create(name: "Monitorar indicadores de desempenho", function: function_48)
  Hability.create(name: "Analisar tendências e variação inesperada", function: function_48)
  Hability.create(name: "Gerenciar ferramentas de orçamento, previsão e plano operacional", function: function_48)
  Hability.create(name: "Atualizar relatórios financeiros trimestrais e mensais", function: function_48)
  Hability.create(name: "Avaliar eficiência de processos", function: function_48)
  Hability.create(name: "Entender o ROI de produtos ou serviços", function: function_48)
  Hability.create(name: "Desenvolver modelos financeiros para apoiar iniciativas estratégicas", function: function_48)
  Hability.create(name: "Apoiar líderes de departamentos com análises detalhadas", function: function_48)
  Hability.create(name: "Preparar apresentações para o conselho de administração", function: function_48)

  function_48 = Function.create(name: 'Planejamento Financeiro', area: area_05)
  Hability.create(name: "Analisar receita, custo, despesas e ganhos de capital", function: function_48)
  Hability.create(name: "Monitorar indicadores de desempenho", function: function_48)
  Hability.create(name: "Analisar tendências e variação inesperada", function: function_48)
  Hability.create(name: "Gerenciar ferramentas de orçamento, previsão e plano operacional", function: function_48)
  Hability.create(name: "Atualizar relatórios financeiros trimestrais e mensais", function: function_48)
  Hability.create(name: "Avaliar eficiência de processos", function: function_48)
  Hability.create(name: "Entender o ROI de produtos ou serviços", function: function_48)
  Hability.create(name: "Desenvolver modelos financeiros para apoiar iniciativas estratégicas", function: function_48)
  Hability.create(name: "Apoiar líderes de departamentos com análises detalhadas", function: function_48)
  Hability.create(name: "Preparar apresentações para o conselho de administração", function: function_48)

  function_49 = Function.create(name: 'Planejamento Estratégico (MKT)', area: area_05)
  Hability.create(name: "Modelar a estratégia e missão da empresa", function: function_49)
  Hability.create(name: "Desenvolver planos de negócio", function: function_49)
  Hability.create(name: "Avaliar ameaças e oportunidades", function: function_49)
  Hability.create(name: "Analisar desempenho operacional da empresa", function: function_49)
  Hability.create(name: "Alinhar recursos e metas de departamento com estratégia geral", function: function_49)
  Hability.create(name: "Suportar mudanças organizacionais", function: function_49)
  Hability.create(name: "Orientar liderança na tomada de decisões eficazes", function: function_49)
  Hability.create(name: "Monitorar tendências do setor e mudanças do mercado", function: function_49)
  Hability.create(name: "Foco em B2B", function: function_49)
  Hability.create(name: "Foco em B2C", function: function_49)
  Hability.create(name: "Foco em C2C", function: function_49)

  # AREA 06
  area_06 = Area.create(name: 'Auditoria, Compliance & Governança')

  # FUNCOES AREA 06
  function_50 = Function.create(name: 'Auditoria Contábil & SOX', area: area_06)
  Hability.create(name: "Planejar e agendar programas de auditoria", function: function_50)
  Hability.create(name: "Rever e avaliar a conclusão das auditorias", function: function_50)
  Hability.create(name: "Analisar dados financeiros, registros, relatórios e declarações", function: function_50)
  Hability.create(name: "Manter e atualizar banco de dados financeiros incluindo descobertas de auditoria", function: function_50)
  Hability.create(name: "Relatar itens de não conformidade", function: function_50)
  Hability.create(name: "Experiência com consultoria externa", function: function_50)
  Hability.create(name: "Experiência com consultoria interna", function: function_50)
  Hability.create(name: "Auditoria com foco em Bancos", function: function_50)
  Hability.create(name: "Auditoria com foco em Seguradoras", function: function_50)
  Hability.create(name: "Auditoria com foco na Indústria", function: function_50)
  Hability.create(name: "Auditoria com foco no setor de Serviços", function: function_50)
  Hability.create(name: "Auditoria de Inventário", function: function_50)

  function_51 = Function.create(name: 'Auditoria de Sistemas de TI', area: area_06)
  Hability.create(name: "Desenvolver um programa de auditoria de Sistemas na organização", function: function_51)
  Hability.create(name: "Analisar riscos associados aos processos de TI", function: function_51)
  Hability.create(name: "Avaliar eficácia dos sistemas de controle interno", function: function_51)
  Hability.create(name: "Estabelecer procedimentos e políticas padrão para auditoria de TI", function: function_51)
  Hability.create(name: "Recomendar ações para itens em não conformidade", function: function_51)
  Hability.create(name: "Experiência com consultoria externa", function: function_51)
  Hability.create(name: "Experiência com consultoria interna", function: function_51)
  Hability.create(name: "Auditoria com foco em Bancos", function: function_51)
  Hability.create(name: "Auditoria com foco em Seguradoras", function: function_51)
  Hability.create(name: "Auditoria com foco na Indústria", function: function_51)
  Hability.create(name: "Auditoria com foco no setor de Serviços", function: function_51)
  Hability.create(name: "Auditoria de Inventário", function: function_51)

  function_52 = Function.create(name: 'Compliance', area: area_06)
  Hability.create(name: "Verificar se diretrizes legais e políticas internas estão sendo cumpridas", function: function_52)
  Hability.create(name: "Avaliar e melhorar a eficiência dos controles", function: function_52)
  Hability.create(name: "Revisar procedimentos e relatórios para mitigar riscos de não conformidade", function: function_52)
  Hability.create(name: "Elaborar, modificar e implementar políticas na empresa", function: function_52)
  Hability.create(name: "Colaborar com conselhos corporativos", function: function_52)
  Hability.create(name: "Preparar relatórios para a liderança e órgãos reguladores externos", function: function_52)
  Hability.create(name: "Atuação com foco em Bancos", function: function_52)
  Hability.create(name: "Atuação com foco em Seguradoras", function: function_52)
  Hability.create(name: "Atuação com foco na Indústria", function: function_52)
  Hability.create(name: "Atuação com foco no setor de Serviços", function: function_52)

  function_53 = Function.create(name: 'Risco Operacional', area: area_06)
  Hability.create(name: "Desenvolver políticas para gerenciamento de riscos operacionais", function: function_53)
  Hability.create(name: "Avaliar riscos operacionais nas unidades de negócios", function: function_53)
  Hability.create(name: "Implementar plano estratégico para previnir, eliminar e mitigar riscos operacionais", function: function_53)
  Hability.create(name: "Definir principais indicadores de risco e controle", function: function_53)
  Hability.create(name: "Investigar causas fundamentais dos riscos operacionais", function: function_53)
  Hability.create(name: "Realizar o mapeamento de riscos", function: function_53)
  Hability.create(name: "Atuação com foco em Bancos", function: function_53)
  Hability.create(name: "Atuação com foco em Seguradoras", function: function_53)
  Hability.create(name: "Atuação com foco na Indústria", function: function_53)
  Hability.create(name: "Atuação com foco no setor de Serviços", function: function_53)

  function_54 = Function.create(name: 'Relacionamento com Investidores', area: area_06)
  Hability.create(name: "Implementar e gerenciar programas de relações com investidores", function: function_54)
  Hability.create(name: "Relacionamento com analistas, investidores e partes interessadas", function: function_54)
  Hability.create(name: "Responder ao questionamento de investidores com respostas corporativas", function: function_54)
  Hability.create(name: "Desenvolver o conteúdo para a apresentação de resultados trimestrais", function: function_54)
  Hability.create(name: "Preparar comunicados à imprensa sobre ganhos trimestrais", function: function_54)
  Hability.create(name: "Comunicar investidores sobre conquiestas e planos da companhia", function: function_54)
  Hability.create(name: "Realizar reuniões presenciais com investidores", function: function_54)

  function_55 = Function.create(name: 'Relações Governamentais', area: area_06)
  Hability.create(name: "Realizar pesqujsas e monitorar a legislação", function: function_55)
  Hability.create(name: "Analisar acontecimentos no governo que podem impactar a organização", function: function_55)
  Hability.create(name: "Pesquisar políticas para ver vantagens e desvantagens no futuro", function: function_55)
  Hability.create(name: "Comunicação interna para liderança da empresa", function: function_55)
  Hability.create(name: "Representação da organização em fóruns ou eventos do setor", function: function_55)
  Hability.create(name: "Reunião com parlamentares para discussão de leis para o setor", function: function_55)
  Hability.create(name: "Relacionamento com a imprensa", function: function_55)

  # AREA 07
  area_07 = Area.create(name: 'Recursos Humanos')

  # FUNCOES AREA 07
  function_56 = Function.create(name: 'Recrutamento e Seleção', area: area_07)
  Hability.create(name: "Contratar posições operacionais", function: function_56)
  Hability.create(name: "Contratar posições de média gerência", function: function_56)
  Hability.create(name: "Contratar posições de altos executivos", function: function_56)
  Hability.create(name: "Relacionamento com consultorias", function: function_56)
  Hability.create(name: "Entrevista por competências", function: function_56)
  Hability.create(name: "Recrutamento interno", function: function_56)
  Hability.create(name: "Recrutamento externo", function: function_56)
  Hability.create(name: "Na área de Finanças & Tributário", function: function_56)
  Hability.create(name: "Na área de Engenharia & Produção", function: function_56)
  Hability.create(name: "Na área de Tecnologia", function: function_56)
  Hability.create(name: "Na área de Vendas & Marketing", function: function_56)
  Hability.create(name: "Na área de Suprimentos, Compras e Logística", function: function_56)
  Hability.create(name: "Na área Jurídica", function: function_56)
  Hability.create(name: "Na área de Recursos Humanos", function: function_56)
  Hability.create(name: "Na área de Mercado Financeiro", function: function_56)

  function_57 = Function.create(name: 'Business Partner', area: area_07)
  Hability.create(name: "Apoiar linha de negócio com questões de RH", function: function_57)
  Hability.create(name: "Analisar tendências e métricas com foco em pessoas", function: function_57)
  Hability.create(name: "Atender reclamações de funcionários", function: function_57)
  Hability.create(name: "Resolver problemas complexos de relacionamento", function: function_57)
  Hability.create(name: "Propor iniciativas para aumentar a produtividade e retenção", function: function_57)
  Hability.create(name: "Fornecer orientação da política de RH", function: function_57)
  Hability.create(name: "Monitorar o planejamento da força de trabalho e sucessão", function: function_57)
  Hability.create(name: "Identificar necessidade de treinamento de indivíduos e equipes", function: function_57)
  Hability.create(name: "Avaliar programas de treinamento", function: function_57)
  Hability.create(name: "Sugeri estratégias para o RH", function: function_57)

  function_58 = Function.create(name: 'Treinamento & Desenvolvimento', area: area_07)
  Hability.create(name: "Estruturar e suportar a avaliação de desempenho dos funcionários", function: function_58)
  Hability.create(name: "Identificar necessidade de treinamento com linha de negócio", function: function_58)
  Hability.create(name: "Desenhar planos de treinamento individual, por equipe, ou geral ", function: function_58)
  Hability.create(name: "Implantar uma ampla variedade de treinamentos", function: function_58)
  Hability.create(name: "Realizar seções efetivas de coaching e orientação", function: function_58)
  Hability.create(name: "Monitorar a eficácia, sucesso e o ROI do programa de treinamento", function: function_58)
  Hability.create(name: "Reunir e compartilhar melhores práticas", function: function_58)
  Hability.create(name: "Estar atualizado com as tendências de treinamento ", function: function_58)
  Hability.create(name: "Gerenciar o orçamento de treinamento", function: function_58)

  function_59 = Function.create(name: 'Remuneração e Benefícios', area: area_07)
  Hability.create(name: "Desenvolver uma política de remuneração consistente com a cultura de trabalho", function: function_59)
  Hability.create(name: "Garantir que as práticas de remuneração estejam em acordo com a legislação", function: function_59)
  Hability.create(name: "Tomar decisões baseadas em dados e metodologia", function: function_59)
  Hability.create(name: "Estruturar remunerações indiretas financeiras, e não financeiras diretas", function: function_59)
  Hability.create(name: "Realizar pesquisas motivacionais para entender alternativas", function: function_59)
  Hability.create(name: "Estruturar cargos e salários, assim como descrições, avaliações e classificações de trabalho", function: function_59)
  Hability.create(name: "Participar de pesquisas salariais de mercado para comparar salários e benefícios vigentes", function: function_59)
  Hability.create(name: "Estruturar e revisar benefícios", function: function_59)

  function_60 = Function.create(name: 'Administração de Pessoal', area: area_07)
  Hability.create(name: "Processar transações da conta da folha de pagamento", function: function_60)
  Hability.create(name: "Coordenar apontamento de horas na folha", function: function_60)
  Hability.create(name: "Analisar alterações na folha de pagamento por novas contratações, recisões e aumentos", function: function_60)
  Hability.create(name: "Garantir conformidade com leis e políticas internas relevantes", function: function_60)
  Hability.create(name: "Suportar auditorias fiscais da folha de pagamento", function: function_60)
  Hability.create(name: "Manter registros atualizados", function: function_60)
  Hability.create(name: "Preparar relatórios", function: function_60)

  # AREA 08
  area_08 = Area.create(name: 'Administrativo & Suporte de escritório')

  # FUNCOES AREA 08
  function_61 = Function.create(name: 'Administrativo', area: area_08)
  Hability.create(name: "Coordenar sistemas administrativos", function: function_61)
  Hability.create(name: "Planejar maneiras de  simplificar processos", function: function_61)
  Hability.create(name: "Organizar o Lay Out do escritório", function: function_61)
  Hability.create(name: "Suportar áreas de negócio com relatórios", function: function_61)
  Hability.create(name: "Gerenciar cronogramas e prazos", function: function_61)
  Hability.create(name: "Monitorar estoque e mateiral de escritório", function: function_61)
  Hability.create(name: "Monitorar custos e despesas administrativas", function: function_61)
  Hability.create(name: "Supervisionar serviços de instalações  e manutenções", function: function_61)
  Hability.create(name: "Organizar eventos", function: function_61)
  Hability.create(name: "Atualizar organograma e informações", function: function_61)
  Hability.create(name: "Atender políticas e regulamentos locais", function: function_61)

  function_62 = Function.create(name: 'Secretariado', area: area_08)
  Hability.create(name: "Gerenciar agenda diária, semanal e mensal", function: function_62)
  Hability.create(name: "Organizar reuniões e compromissos", function: function_62)
  Hability.create(name: "Preparar e divulgar correspondências, formulários e memorando", function: function_62)
  Hability.create(name: "Arquivar e atualizar contatos de funcionários, clientes e parceiros externos", function: function_62)
  Hability.create(name: "Registrar a ata de reuniões", function: function_62)
  Hability.create(name: "Suportar a elebaração de relatórios regulares", function: function_62)
  Hability.create(name: "Desenvolver e manter um sistema de arquivamento", function: function_62)
  Hability.create(name: "Verificar e pedir material de escritório", function: function_62)
  Hability.create(name: "Organizar viagens", function: function_62)
  Hability.create(name: "Documentar despesas e entregar relatórios", function: function_62)

  function_63 = Function.create(name: 'Facilities', area: area_08)
  Hability.create(name: "Coordenar instalações como eletricidade, aquecimento, telecomunicações, etc", function: function_63)
  Hability.create(name: "Gerenciar manutenção de equipamentos e suprimentos ", function: function_63)
  Hability.create(name: "Atender padrões de saúde e segurança", function: function_63)
  Hability.create(name: "Realizar inspeções para determinar necessidade de reparos e reformas", function: function_63)
  Hability.create(name: "Analisar o consumo de utilitários", function: function_63)
  Hability.create(name: "Supervisionar todos os funcionários e terceiros relacionados", function: function_63)
  Hability.create(name: "Controlar espaço de estacionamento, tratamento de resíduos e segurança do edifício", function: function_63)
  Hability.create(name: "Lidar com planos de seguros e contratos de serviços", function: function_63)
  Hability.create(name: "Gerenciar o orçamento da área", function: function_63)

  function_64 = Function.create(name: 'Operação e Administração de Vendas - Gerente', area: area_08)
  Hability.create(name: "Processar pedidos", function: function_64)
  Hability.create(name: "Verificar dados em pedidos e faturas", function: function_64)
  Hability.create(name: "Entrar em contato para obter informações", function: function_64)
  Hability.create(name: "Garantir entrega em tempo hábil", function: function_64)
  Hability.create(name: "Manter e atualizar registro de vendas para clientes", function: function_64)
  Hability.create(name: "Desenvolver relatórios de vendas mensais", function: function_64)
  Hability.create(name: "Informar opniões de clientes internamente", function: function_64)
  Hability.create(name: "Analisar metas e atingimento de vendas", function: function_64)

  # AREA 09
  area_09 = Area.create(name: 'TI: Infraestrutura, Suporte, Redes e Telecom')

  # FUNCOES AREA 09
  function_65 = Function.create(name: 'Infraestrutura', area: area_09)
  Hability.create(name: "Gerenciar banco de dados", function: function_65)
  Hability.create(name: "Gerenciar servidores", function: function_65)
  Hability.create(name: "Supervisionar armazenamento na Núvem", function: function_65)
  Hability.create(name: "Suportar ERPS", function: function_65)
  Hability.create(name: "Suportar chamadas de help desk ", function: function_65)
  Hability.create(name: "Administrar redes", function: function_65)
  Hability.create(name: "Cuidar da segurança da informação", function: function_65)
  Hability.create(name: "Gerenciar equipamentos e planos de telefonia", function: function_65)
  Hability.create(name: "Estruturar plano de contingência", function: function_65)
  Hability.create(name: "Contratar prestadores de serviços", function: function_65)
  Hability.create(name: "Administrar orçamento", function: function_65)
  Hability.create(name: "Redigir políticas e procedimentos", function: function_65)
  Hability.create(name: "Moritorar e reportar não conformidades", function: function_65)

  function_66 = Function.create(name: 'Segurança', area: area_09)
  Hability.create(name: "Manter políticas e procedimentos de segurança da informação", function: function_66)
  Hability.create(name: "Controlar perfis e níveis de acesso", function: function_66)
  Hability.create(name: "Atender as metas e padrões da segurança da organização", function: function_66)
  Hability.create(name: "Identificar riscos de segurança e resolvê-los", function: function_66)
  Hability.create(name: "Atualizar a organização sobre práticas seguras", function: function_66)
  Hability.create(name: "Monitorar sistemas internos de controle", function: function_66)
  Hability.create(name: "Realizar testes de invasão preventivos", function: function_66)
  Hability.create(name: "Controlar acesso remoto ", function: function_66)
  Hability.create(name: "Proteger informação em dispositivos de terceiros", function: function_66)

  function_67 = Function.create(name: 'Arquiteto de Redes', area: area_09)
  Hability.create(name: "Projetar redes WAN, LAN e outros sistemas de dados", function: function_67)
  Hability.create(name: "Testar e avaliar redes", function: function_67)
  Hability.create(name: "Analisar requisitos de negócios", function: function_67)
  Hability.create(name: "Realizar modelagem, análise e planejamento de redes", function: function_67)
  Hability.create(name: "Instalar equipamentos de hardware", function: function_67)
  Hability.create(name: "Desenvolver rotas de dados", function: function_67)
  Hability.create(name: "Configurar drivers para redes de software", function: function_67)
  Hability.create(name: "Gerenciar fornecedores de tecnologia", function: function_67)

  function_68 = Function.create(name: 'Administrador de Redes', area: area_09)
  Hability.create(name: "Configurar e atualizar redes e servidores internos", function: function_68)
  Hability.create(name: "Instalar e integrar novos aplicativos ", function: function_68)
  Hability.create(name: "Suportar e administrar aplicativos de terceiros", function: function_68)
  Hability.create(name: "Garantir segurança e conectividade de rede", function: function_68)
  Hability.create(name: "Monitorar desempenho de rede", function: function_68)
  Hability.create(name: "Configurar contas de usuários, permissões e senhas", function: function_68)
  Hability.create(name: "Resolver problemas de usuários", function: function_68)
  Hability.create(name: "Especificar requisitos de sistemae soluções de design", function: function_68)

  function_69 = Function.create(name: 'Help Desk e Suporte', area: area_09)
  Hability.create(name: "Fornecer suporte de 1o nível", function: function_69)
  Hability.create(name: "Fornecer suporte de 2o nível", function: function_69)
  Hability.create(name: "Fornecer suporte de 3o nível", function: function_69)
  Hability.create(name: "Rastrear, rotear e redirecionar chamados ", function: function_69)
  Hability.create(name: "Solicitar próximo nível em problemas não resolvidos", function: function_69)
  Hability.create(name: "Atualizar dados de usuários", function: function_69)
  Hability.create(name: "Produzir relatórios de atividades", function: function_69)

  function_70 = Function.create(name: 'Engenheiro de Telecomunicações', area: area_09)
  Hability.create(name: "Qualificar equipamentos e informar autoridades em caso de alteração", function: function_70)
  Hability.create(name: "Projetar e construir o sistema de comunicações", function: function_70)
  Hability.create(name: "Atender legislação e normas vigentes", function: function_70)
  Hability.create(name: "Antecipar e prevenir potenciais problemas", function: function_70)
  Hability.create(name: "Identificar e suportar problemas técnicos", function: function_70)
  Hability.create(name: "Visitar e realizar manutenção no local", function: function_70)
  Hability.create(name: "Atuar prontamente em situações de urgência", function: function_70)
  Hability.create(name: "Instalar circuitos e  sistemas de telecomunicações", function: function_70)
  Hability.create(name: "Selecionar equipamentos a serem adquiridos", function: function_70)

  # AREA 10
  area_10 = Area.create(name: 'TI: Banco de dados e Analytics')

  # FUNCOES AREA 10
  function_71 = Function.create(name: 'Operações de Datacenter', area: area_10)
  Hability.create(name: "Realizar manutenção preventiva no Datacenter", function: function_71)
  Hability.create(name: "Administrar solicitações de serviços", function: function_71)
  Hability.create(name: "Gerenciar processos críticos ", function: function_71)
  Hability.create(name: "Documentar registro de equipamentos", function: function_71)
  Hability.create(name: "Administrar equipamentos de backup", function: function_71)
  Hability.create(name: "Manter estoque de equipamentos", function: function_71)
  Hability.create(name: "Gerenciar problemas recorrentes ", function: function_71)

  function_72 = Function.create(name: 'Administrador de Banco de Dados (DBA)', area: area_10)
  Hability.create(name: "Construir sistemas de banco de dados", function: function_72)
  Hability.create(name: "Definir usuários e ativar dados correspondentes", function: function_72)
  Hability.create(name: "Recuperar dados em backups", function: function_72)
  Hability.create(name: "Minimizar tempo de inatividade do banco", function: function_72)
  Hability.create(name: "Forncer suporte de gerenciamento de dados aos usuários", function: function_72)
  Hability.create(name: "Documentar políticas, procedimentos e padrões", function: function_72)
  Hability.create(name: "Relaizar testes e avaliações", function: function_72)
  Hability.create(name: "Garantir segurança, privacidade e integridade dos dados", function: function_72)

  function_73 = Function.create(name: 'Arquitetura de dados', area: area_10)
  Hability.create(name: "Desenvolver soluções de banco de dados", function: function_73)
  Hability.create(name: "Instalar e configurar sistemas de informação", function: function_73)
  Hability.create(name: "Analisar requisitos estruturais de novos aplicativos", function: function_73)
  Hability.create(name: "Migrar dados de sistemas legados para novas soluções", function: function_73)
  Hability.create(name: "Modelar dados conceituais e lógicos e fluxogramas", function: function_73)
  Hability.create(name: "Melhorar desempenho do sistema ", function: function_73)
  Hability.create(name: "Resolver problemas de integração", function: function_73)
  Hability.create(name: "Definir procedimentos de segurança e backup", function: function_73)
  Hability.create(name: "Fornecer suporte operacional para infomações gerenciais", function: function_73)

  function_74 = Function.create(name: 'Business Inteligence', area: area_10)
  Hability.create(name: "Elaborar relatórios para suportar o negócio", function: function_74)
  Hability.create(name: "Desenvolver aplicações para atender necessidades de clientes", function: function_74)
  Hability.create(name: "Implementar sistemas de datawarehouse para análises de BI", function: function_74)
  Hability.create(name: "Construir dashboards para apresentação de resultados", function: function_74)
  Hability.create(name: "Analisar dados históricos e criar relatórios e KPIs", function: function_74)
  Hability.create(name: "Utilizar ferramentas de BI para efetuar análises", function: function_74)
  Hability.create(name: "Construir tabelas dinâmicas", function: function_74)
  Hability.create(name: "Identificar tendências de mercado e oportunidades", function: function_74)

  function_75 = Function.create(name: 'Cientista de dados', area: area_10)
  Hability.create(name: "Processar alto volume de dados (Big Data)", function: function_75)
  Hability.create(name: "Estimar tendências futuras", function: function_75)
  Hability.create(name: "Realizar análise estatíscas", function: function_75)
  Hability.create(name: "Utilizar modelos e ferramentas complexas de análise", function: function_75)
  Hability.create(name: "Analisar dados não estruturados", function: function_75)
  Hability.create(name: "Criar cenários sobre futuras possibilidades", function: function_75)
  Hability.create(name: "Investigar novas possibilidades através de dados", function: function_75)

  # AREA 11
  area_11 = Area.create(name: 'TI: Banco de dados e Analytics')

  # FUNCOES AREA 11
  function_76 = Function.create(name: 'Arquitetura de Software', area: area_11)
  Hability.create(name: "Desenvolver especificações de alto nível", function: function_76)
  Hability.create(name: "Integrar e viabilizar o sistema", function: function_76)
  Hability.create(name: "Avaliar todos os aspectos do desenvolvimento", function: function_76)
  Hability.create(name: "Definir padrões de codificação", function: function_76)
  Hability.create(name: "Estruturar o fluxo de trabalho", function: function_76)
  Hability.create(name: "Acompanhar a evolução com diretrizes", function: function_76)
  Hability.create(name: "Atender requisitos de segurança e atualizações", function: function_76)
  Hability.create(name: "Aprovar produto final", function: function_76)

  function_77 = Function.create(name: 'UX/ UI', area: area_11)
  Hability.create(name: "Avaliar requisitos do usuário", function: function_77)
  Hability.create(name: "Ilustrar ideias de design usando ferramentas", function: function_77)
  Hability.create(name: "Projetar elementos gráficos da interface do usuário", function: function_77)
  Hability.create(name: "Construit a navebilidade e campos de pesquisa", function: function_77)
  Hability.create(name: "Desenvolver maquetes e protótipos de UI", function: function_77)
  Hability.create(name: "Criar designs gráficos originais", function: function_77)
  Hability.create(name: "Identificar e ajustar problemas de UX", function: function_77)
  Hability.create(name: "Definir estilo por meio de fontes, cores e imagens", function: function_77)

  function_78 = Function.create(name: 'Desenvolvimento Front End', area: area_11)
  Hability.create(name: "Usar linguagens de Front End para criar páginas", function: function_78)
  Hability.create(name: "Otimizar velocidade dos aplicativos", function: function_78)
  Hability.create(name: "Projetar recursos para Desktop e dispositivos móveis", function: function_78)
  Hability.create(name: "Colaborar com desenvolvedores de Back End ", function: function_78)
  Hability.create(name: "Obter opniniões de usuários para melhorias", function: function_78)
  Hability.create(name: "Escrever docimentos e guias de requisitos funcionais", function: function_78)
  Hability.create(name: "Criar modelos e protótipos de qualidade", function: function_78)

  function_79 = Function.create(name: 'Desenvolvimento Back End', area: area_11)
  Hability.create(name: "Codificar e depurar o aplicativo", function: function_79)
  Hability.create(name: "Solucionar problemas de execução", function: function_79)
  Hability.create(name: "Realizar testes de interface com usuário", function: function_79)
  Hability.create(name: "Desenvolver a lógica e algorítimos do sistema", function: function_79)
  Hability.create(name: "Escrever códigos e bibliotecas reutilizáveis", function: function_79)
  Hability.create(name: "Auxiliar o Front End com a lógica do servidor", function: function_79)

  function_80 = Function.create(name: 'Desenvolvimento Full Stack', area: area_11)
  Hability.create(name: "Projetar estrutura geral do aplicativo", function: function_80)
  Hability.create(name: "Desenvolver para dispositivos Móveis e Desktops", function: function_80)
  Hability.create(name: "Integrar Front End e Back End", function: function_80)
  Hability.create(name: "Desenvolver estruutra completa do aplicativo", function: function_80)
  Hability.create(name: "Manter a integridade e organização do código", function: function_80)

  function_81 = Function.create(name: 'Desenvolvimento Mobile', area: area_11)
  Hability.create(name: "Produzir aplicativos móveis ", function: function_81)
  Hability.create(name: "Suportar o ciclo de vida da aplicação", function: function_81)
  Hability.create(name: "Avaliar requisitos e sugerir soluções", function: function_81)
  Hability.create(name: "Solicitar testes e resolver erros", function: function_81)
  Hability.create(name: "Melhorar experiência do usuário", function: function_81)
  Hability.create(name: "Sugerir tendências de mercado", function: function_81)
  Hability.create(name: "Disponibilizar produto em lojas de aplicativos", function: function_81)

  function_82 = Function.create(name: 'Devops', area: area_11)
  Hability.create(name: "Integrar desenvolvimento, operações e infraestrutura", function: function_82)
  Hability.create(name: "Realizar atualizações e correções", function: function_82)
  Hability.create(name: "Construir ferramentas para minimizar erros", function: function_82)
  Hability.create(name: "Entender a causa raiz em erros de produção", function: function_82)
  Hability.create(name: "Investigar e resolver problemas técnicos", function: function_82)
  Hability.create(name: "Desenvolver scripts para automatizar a visualização", function: function_82)
  Hability.create(name: "Elaborar procedimentos de manutenção", function: function_82)

  function_83 = Function.create(name: 'Testes e Qualidade', area: area_11)
  Hability.create(name: "Revisar especificações e documentos técnicos ", function: function_83)
  Hability.create(name: "Criar e executar planos de teste", function: function_83)
  Hability.create(name: "Identificar, rastrear e documentar problemas", function: function_83)
  Hability.create(name: "Realizar testes após correção de erros", function: function_83)
  Hability.create(name: "Monitorar resultados do processo de depuração", function: function_83)
  Hability.create(name: "Estar atulizado com ferramentas de testes", function: function_83)
  Hability.create(name: "Atender métricas de qualidade para quantidade e resolução de erros", function: function_83)

  function_84 = Function.create(name: 'Dono do Produto', area: area_11)
  Hability.create(name: "Planjear e evoluir o produto", function: function_84)
  Hability.create(name: "Fornecer visão e direção para desenvolvimento ágil", function: function_84)
  Hability.create(name: "Garantir tarefas para desenvolvimento", function: function_84)
  Hability.create(name: "Transmitir a visão do produto", function: function_84)
  Hability.create(name: "Propor melhorias e adpatações", function: function_84)

  function_85 = Function.create(name: 'Scrum Master', area: area_11)
  Hability.create(name: "Orientar equipe na metodologia ágil", function: function_85)
  Hability.create(name: "Promover a auto organização do time", function: function_85)
  Hability.create(name: "Remover impedimentos para produção", function: function_85)
  Hability.create(name: "Facilitar a discussão e tomada de decisões", function: function_85)
  Hability.create(name: "Resolver potenciais conflitos", function: function_85)
  Hability.create(name: "Auxiliar nas pendências do produto", function: function_85)

  function_86 = Function.create(name: 'Agile Coach', area: area_11)
  Hability.create(name: "Transmitir a metodolia ágil para a equipe", function: function_86)
  Hability.create(name: "Fornecer treinamento na metodologia", function: function_86)
  Hability.create(name: "Atuar como mentor nos projetos", function: function_86)
  Hability.create(name: "Verificar se as equipes estão usando a metodologia", function: function_86)
  Hability.create(name: "Indentificar e escalar riscos do projeto", function: function_86)
  Hability.create(name: "Suportar o responsável pelo produto", function: function_86)
  Hability.create(name: "Acompanhar o Scrum Master em ativididades", function: function_86)

  # AREA 12
  area_12 = Area.create(name: 'TI: Aplicações, CRMs e ERPs')

  # FUNCOES AREA 12
  function_87 = Function.create(name: 'Aplicações', area: area_12)
  Hability.create(name: "Entender demandas de negócio para oferecer soluções", function: function_87)
  Hability.create(name: "Monitorar operações diárias das equipes de desenvolvimento", function: function_87)
  Hability.create(name: "Trazer feedback para a equipe de operação", function: function_87)
  Hability.create(name: "Analisar requisitos de negócio e sugeir melhorias", function: function_87)
  Hability.create(name: "Gerenciar projetos de aplicativos e custos", function: function_87)
  Hability.create(name: "Administrar programas", function: function_87)
  Hability.create(name: "Auxliar departamentos internos ", function: function_87)

  function_88 = Function.create(name: 'Gerenciamento de Projetos', area: area_12)
  Hability.create(name: "Garantir projetos dentro do prazo e escopo", function: function_88)
  Hability.create(name: "Disponibilizar e alocar recursos internos e terceiros", function: function_88)
  Hability.create(name: "Gerenciar o orçamento do projeto", function: function_88)
  Hability.create(name: "Allinhar partes interessadas para garantir viabilidade técnica", function: function_88)
  Hability.create(name: "Acompanhar custos e orçamento do projeto", function: function_88)
  Hability.create(name: "Medir desempenho do projeto por métricas", function: function_88)
  Hability.create(name: "Minimizar riscos ao projeto", function: function_88)
  Hability.create(name: "Documentar plano e atividades", function: function_88)

  function_89 = Function.create(name: 'Levantamento de Requisitos', area: area_12)
  Hability.create(name: "Atuar como facilitador entre negócio e TI", function: function_89)
  Hability.create(name: "Levantar requisitos com usuários", function: function_89)
  Hability.create(name: "Sugerir modificações para melhor experiência do usuário", function: function_89)
  Hability.create(name: "Fornecer suporte e treinamento na implementação", function: function_89)
  Hability.create(name: "Colaborar com o desenvolvimento do projeto", function: function_89)

  function_90 = Function.create(name: 'Consultoria de Aplicações', area: area_12)
  Hability.create(name: "Desenvolver novas aplicações e programas", function: function_90)
  Hability.create(name: "Customizar a aplicação para a empresa", function: function_90)
  Hability.create(name: "Atualizar versões de aplicações", function: function_90)
  Hability.create(name: "Implementar soluções para erros existentes", function: function_90)
  Hability.create(name: "Desenvolver novas funcionalidades para atender o cliente", function: function_90)
  Hability.create(name: "Fornecer suporte técnico", function: function_90)
  Hability.create(name: "Treinar usuários e equipes", function: function_90)
end

# -------
# Creating First Title List
# -------
if TitleList.count == 0
  TitleList.create(name: 'Analista', priority: 1)
  TitleList.create(name: 'Especialista', priority: 2)
  TitleList.create(name: 'Consultor', priority: 3)
  TitleList.create(name: 'Coordenador', priority: 4)
  TitleList.create(name: 'Gerente', priority: 5)
  TitleList.create(name: 'Gerente Sr', priority: 6)
  TitleList.create(name: 'Diretor', priority: 7)
end

# -------
# Creating First Range List
# -------
if RangeList.count == 0
  RangeList.create(name: 'Anos')
  RangeList.create(name: 'Meses')
end

# -------
# Creating First Education List
# -------
if EducationList.count == 0
  EducationList.create(name: 'Técnico Completo')
  EducationList.create(name: 'Superior Incompleto')
  EducationList.create(name: 'Superior Completo')
  EducationList.create(name: 'Pós graduação ou MBA')
  EducationList.create(name: 'Mestrado')
  EducationList.create(name: 'Doutorado')
end

# -------
# Creating First Language List
# -------
if LanguageList.count == 0
  LanguageList.create(name: 'Inglês')
  LanguageList.create(name: 'Espanhol')
  LanguageList.create(name: 'Alemão')
  LanguageList.create(name: 'Francês')
  LanguageList.create(name: 'Português')
  LanguageList.create(name: 'Italiano')
  LanguageList.create(name: 'Japonês')
  LanguageList.create(name: 'Mandarim')
  LanguageList.create(name: 'Coreano')
end

# -------
# Creating First Language Leve List
# -------
if LanguageLevelList.count == 0
  LanguageLevelList.create(name: 'lidero reuniões presenciais ou remotas para a resolução de problemas complexos')
  LanguageLevelList.create(name: 'participo de reuniões como ouvinte e com contribuições pontuais')
  LanguageLevelList.create(name: 'Somente por email')
end

# -------
# Creating First Nofsalaries List
# -------
if NofsalariesList.count == 0
  NofsalariesList.create(name: 'PJ (12 salários / ano)', value: 12)
  NofsalariesList.create(name: 'CLT (13,33 salários / ano)', value: 13.33)
end

# -------
# Update Nofsalaries List if it already created (just in case this seed ran before 2018 Sep 24)
# -------
if NofsalariesList.count == 2
  NofsalariesList.find(1).update_attributes(value: 12)
  NofsalariesList.find(2).update_attributes(value: 13.33)
end

# -------
# Creating First Benefits List
# -------
if BenefitsList.count == 0
  BenefitsList.create(name: 'Plano de saúde')
  BenefitsList.create(name: 'Vale transporte')
  BenefitsList.create(name: 'Ticket Refeição')
  BenefitsList.create(name: 'Plano odontológico')
  BenefitsList.create(name: 'Estacionamento')
  BenefitsList.create(name: 'Vale supermercado')
  BenefitsList.create(name: 'Seguro de vida')
  BenefitsList.create(name: 'Previdência privada')
  BenefitsList.create(name: 'Veículo')
  BenefitsList.create(name: 'Bolsa de estudos')
  BenefitsList.create(name: 'Ações')
end

# -------
# Creating First Annual Claim Rate List
# -------
if AnnualClaimRateList.count == 0
  AnnualClaimRateList.create(name: '30% de aumento ou mais', value: 30)
  AnnualClaimRateList.create(name: '20% de aumento ou mais', value: 20)
  AnnualClaimRateList.create(name: '10% de aumento ou mais', value: 10)
  AnnualClaimRateList.create(name: 'A partir do mesmo', value: 0)
  AnnualClaimRateList.create(name: '10% a menos', value: -10)
  AnnualClaimRateList.create(name: '20% a menos', value: -20)
  AnnualClaimRateList.create(name: '30% a menos', value: -30)
end

# -------
# Creating First Status List
# -------
if StatusList.count == 0
  StatusList.create(name: 'Interessado')
  StatusList.create(name: 'Em processo')
  StatusList.create(name: 'Aprovados')
  StatusList.create(name: 'Eliminados')
  StatusList.create(name: 'Arquivados')
end

# -------
# Creating First Step List
# -------
if StepList.count == 0
  StepList.create(name: 'Selecionados')
  StepList.create(name: '1ª etapa')
  StepList.create(name: '2ª etapa')
  StepList.create(name: 'Última etapa')
  StepList.create(name: 'Proposta')
  StepList.create(name: 'Aprovados')
end

# -------
# Creating First Sort List
# -------
if SortList.count == 0
  SortList.create(name: 'Maior Remuneração Anual')
  SortList.create(name: 'Menor Remuneração Anual')
  SortList.create(name: 'Maior Remuneração Mensal')
  SortList.create(name: 'Menor Remuneração Mensal')
  SortList.create(name: 'Maior Tempo de Carreira')
  SortList.create(name: 'Menor Tempo de Carreira')
end

# -------
# Update Annual Claim Rate List (2018 Sep 25)
# -------
if AnnualClaimRateList.count == 7 && AnnualClaimRateList.where("value IS ?", nil).present?
  AnnualClaimRateList.find_by_name('30% de aumento ou mais').update_attributes(value: 30)
  AnnualClaimRateList.find_by_name('20% de aumento ou mais').update_attributes(value: 20)
  AnnualClaimRateList.find_by_name('10% de aumento ou mais').update_attributes(value: 10)
  AnnualClaimRateList.find_by_name('A partir do mesmo').update_attributes(value: 0)
  AnnualClaimRateList.find_by_name('10% a menos').update_attributes(value: -10)
  AnnualClaimRateList.find_by_name('20% a menos').update_attributes(value: -20)
  AnnualClaimRateList.find_by_name('30% a menos').update_attributes(value: -30)
end